import type { Metadata } from "next";
import "./globals.css";
import { sans_serif } from "./fonts";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sans_serif.className}  antialiased`}>
        <Toaster />
        <nav>{/* <Navbar /> */}</nav> {children}
      </body>
    </html>
  );
}
